file_format: "1"
id: atreoid_vi
name: Atreoid Vi
type: shield
requires: [nice_nano_v2]
exposes: [nice_view_header]
features:
  - keys
  - display
outputs:
  - usb
  - ble
url: https://sfcgeorge.co.uk
